server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30天过期
    session:
      cookie:
        max-age: 2592000
spring:
  application:
    name: picture-backend
  servlet:
    multipart:
      max-file-size: 10MB
  profiles:
    active: @activatedProperties@
  session:
    store-type: redis
    # session 30天过期
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_picture
    username: root
    password: oukele
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    timeout: 5000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 仅在开发环境下打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局逻辑删除实体字段名
      logic-delete-field: isDelete
      # 逻辑已删除值（默认为1）
      logic-delete-value: 1
      # 逻辑未删除值（默认为0）
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: "picture-backend接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.oukele.picturebackend.controller
